APP/Areas/Main/Controllers/TestController.cs
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Utility;

namespace APP.Areas.Main.Controllers
{
    [Area("Main")]
    [Authorize(Roles = SD.RoleAdmin)]
    public class TestController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<TestController> _logger;
        public readonly IWebHostEnvironment _hostEnvironment;
        public TestController(ILogger<TestController> logger, IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Test test)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        string webRootPath = _hostEnvironment.WebRootPath;
                        var files = HttpContext.Request.Form.Files;
                        if (files.Count > 0)
                        {
                            string fileName = Guid.NewGuid().ToString();
                            var uploads = Path.Combine(webRootPath, @"img\checkUp");
                            var extenstion = Path.GetExtension(files[0].FileName);



                            using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                            {
                                files[0].CopyTo(filesStreams);
                            }
                            test.ImgUrl = @"\img\checkUp\" + fileName + extenstion;
                        }
                        var tst = new Test()
                        {
                            ImgUrl = test.ImgUrl,

                            Name = test.Name,
                            Price = test.Price,
                            Description = test.Description,
                            ModelName = test.ModelName,
                            CurStatus=SD.Active


                        };
                        await _unitOfWork.Tests.AddAsync(tst);
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(test);
        }

        public async Task<IActionResult> EditTest(string id)
        {
            var test = await _unitOfWork.Tests.GetFirstOrDefaultAsync(a => a.Id == Convert.ToInt32(id));
            if (test == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(test);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTest(Test test)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    try
                    {
                        string webRootPath = _hostEnvironment.WebRootPath;
                        var files = HttpContext.Request.Form.Files;
                        if (files.Count > 0)
                        {
                            string fileName = Guid.NewGuid().ToString();
                            var uploads = Path.Combine(webRootPath, @"img\checkUp");
                            var extenstion = Path.GetExtension(files[0].FileName);

                            if (test.ImgUrl != null)
                            {

                                var imagePath = Path.Combine(webRootPath, test.ImgUrl.TrimStart('\\'));
                                if (System.IO.File.Exists(imagePath))
                                {
                                    System.IO.File.Delete(imagePath);
                                }
                            }
                            using (var filesStreams = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                            {
                                files[0].CopyTo(filesStreams);
                            }
                            test.ImgUrl = @"\img\checkUp\" + fileName + extenstion;
                        }
                        var book = await _unitOfWork.Tests.GetFirstOrDefaultAsync(a => a.Id == test.Id);

                        book.ImgUrl = test.ImgUrl;
                        book.Name = test.Name;
                        book.Price = test.Price;
                        book.ModelName = test.ModelName;
                        book.Description = test.Description;
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }

                }
            }

            return View(test);
        }
        #region JS Calls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var objList = await _unitOfWork.Tests.GetAllAsync(a=>a.CurStatus==SD.Active);
            return Json(new { data = objList });
        }

        #endregion
    }
}

APP/Areas/Main/Controllers/UserController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Models;
using Models.ViewModels;
using Utility;

namespace APP.Areas.Main.Controllers
{
    [Authorize(Roles = SD.RoleAdmin)]
    [Area("Main")]
    public class UserController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<UserController> _logger;
        public readonly IWebHostEnvironment _hostEnvironment;

        public UserController(ILogger<UserController> logger, IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, IWebHostEnvironment hostEnvironment)
        {

            _hostEnvironment = hostEnvironment;
            _roleManager = roleManager;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _logger = logger;
   
        }
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult ViewPermissions()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult CustomerDetails()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUserVM applicationUserVM)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    //!Do not always use transaction, use only if there are more than one SaveAsync() calls
                    try
                    {
                        var claimsIdentity = (ClaimsIdentity)User.Identity;
                        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                        var logedInUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == claim.Value);

                        string userKey = Guid.NewGuid().ToString();
                        var applicationUser = new ApplicationUser
                        {
                            UserName = applicationUserVM.Email,
                            Email = applicationUserVM.Email,
                            EmailConfirmed = true,
                            FirstName = applicationUserVM.FirstName,
                            LastName = applicationUserVM.LastName,
                            CreatedBy = logedInUser.Email,
                            CreatedOnUTC = DateTime.UtcNow,
                            Role = applicationUserVM.Role
                        };
                        var result = await _userManager.CreateAsync(applicationUser, applicationUserVM.Password);

                        if (result.Succeeded)
                        {
                            var user = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == applicationUser.Id);
                            await _userManager.AddToRoleAsync(user, applicationUserVM.Role);
                           

                            _unitOfWork.CommitAsync(transaction);
                            return RedirectToAction(nameof(Index));
                        }
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                    catch (System.Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }
                }
            }
            return View(applicationUserVM);
        }
        public async Task<IActionResult> ResetPassword(string id)
        {
            RestPasswordVM restPasswordVM = new RestPasswordVM()
            {
                ApplicationUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == id)
            };
            var code = await _userManager.GeneratePasswordResetTokenAsync(restPasswordVM.ApplicationUser);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            restPasswordVM.Code = code;

            return View(restPasswordVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(RestPasswordVM restPasswordVM)
        {
            if (ModelState.IsValid)
            {
                var user = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == restPasswordVM.ApplicationUser.Id);
                var code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(restPasswordVM.Code));
                var result = await _userManager.ResetPasswordAsync(user, code, restPasswordVM.Password);
            }
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> ViewCustomer(string id)
        {
            var user = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == id);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ViewCustomer(ApplicationUser user)
        {
            using (var transaction = await _unitOfWork.BeginTransactionAsync())
            {
                try
                {
                    var claimsIdentity = (ClaimsIdentity)User.Identity;
                    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                    var logedInUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == claim.Value);

                    var appUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == user.Id);
                    appUser.UpdatedBy = logedInUser.Id;
                    appUser.UpdatedOnUTC = DateTime.UtcNow;
                    appUser.CurStatus = appUser.CurStatus == SD.Active ? SD.DeActive : SD.Active;
                    _unitOfWork.ApplicationUser.Update(appUser);
                    _unitOfWork.SaveAsync();
                    _unitOfWork.CommitAsync(transaction);

                }
                catch (System.Exception)
                {
                    _unitOfWork.RollbackAsync(transaction);
                    return StatusCode(StatusCodes.Status500InternalServerError);
                }
            }
            return RedirectToAction(nameof(CustomerDetails));
        }
        public async Task<IActionResult> EditProfile(string id)
        {
            var user = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                using (var transaction = await _unitOfWork.BeginTransactionAsync())
                {
                    //!Do not always use transaction, use only if there are more than one SaveAsync() calls
                    try
                    {
                        var claimsIdentity = (ClaimsIdentity)User.Identity;
                        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                        var logedInUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == claim.Value);

                        var appUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(a => a.Id == user.Id);
                        appUser = user;
                        appUser.UpdatedBy = logedInUser.Id;
                        appUser.UpdatedOnUTC = DateTime.UtcNow;
                        _unitOfWork.ApplicationUser.Update(appUser);
                        _unitOfWork.SaveAsync();
                        _unitOfWork.CommitAsync(transaction);
                    }
                    catch (System.Exception)
                    {
                        _unitOfWork.RollbackAsync(transaction);
                        return StatusCode(StatusCodes.Status500InternalServerError);
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var data = from a in await _unitOfWork.ApplicationUser.GetAllAsync()
                       where a.Role==SD.RoleAdmin || a.Role==SD.RoleTechnician
                       select new
                       {
                           a.Email,
                           name = $"{a.FirstName} {a.LastName}",
                           a.Id
                       };
            return Json(new { data });
        }
        [HttpGet]
        public async Task<IActionResult> GetAllCustomers()
        {
            var data = from a in await _unitOfWork.ApplicationUser.GetAllAsync()
                       where a.Role==SD.RoleCustomer
                       select new
                       {
                           a.Email,
                           name = $"{a.FirstName} {a.LastName}",
                           a.Id
                       };
            return Json(new { data });
        }

        [HttpGet]

APP/ViewComponents/UserNameAdminViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace RuhunuFarms.ViewComponents
{
    public class UserNameViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public UserNameViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userFromDb = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(u => u.Id == claims.Value);

            return View(userFromDb);
        }
    }
}

APP/Views/Shared/_Cart.cshtml
@using APP.Session
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContext

<li class="dropdown">
    
</li><!--/.dropdown-->

APP/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" id="btnCreate" class="btn btn-success form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" id="btnBackToList" class="btn btn-info form-control">Back to List</a>
    </div>
</div>

APP/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" id="btnUpdate" class="btn btn-warning form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" id="btnBackToList" class="btn btn-info form-control">Back to List</a>
    </div>
</div>

APP/Views/Shared/_LayoutMain.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ABC Labs </title>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"> 
    <link rel="stylesheet"
        href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bundles/style.min.css">
    @await RenderSectionAsync("Styles", required: false)

<style>
    [class*=sidebar-dark-] {
        background-color: #440000;
    }
</style>
</head>


<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom-0">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <partial name="_LoginPartial" />
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary">
            <!-- Brand Logo -->
            <a href="~/template/index3.html" class="brand-link border-bottom-0">
                <img src="~/template/dist/img/Logo.jpg" alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light font-weight-bold">ABC Clinic</span>
            </a>


            <!-- Sidebar -->
            <div class="sidebar text-sm">
                <!-- Sidebar user (optional) -->
                @if (SignInManager.IsSignedIn(User))
                {
                    @await Component.InvokeAsync("UserName")
                }

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->

                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Home" asp-area="Main" class="nav-link">
                                <i class="nav-icon fas fa-chalkboard-teacher"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-envelope-open-text"></i>
                                <p>
                                    Check Up Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Test" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Check Up</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Create" asp-controller="Test" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Create Check Up</p>
                                    </a>
                                </li>
                            </ul>

                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-calendar"></i>
                                <p>
                                    Appoinment Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="ViewPaidOrder" asp-controller="Home" asp-area="Lab" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Create Report</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="ViewNonPaidOrder" asp-controller="Home" asp-area="Lab" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Pay Appoinment</p>
                                    </a>
                                </li>
                            </ul>

                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-calendar"></i>
                                <p>
                                    Query Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Queries" asp-area="Lab" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Query List</p>
                                    </a>
                                </li>
                            </ul>


                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-receipt"></i>
                                <p>
                                    Reports Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Due Bills</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="SalesInvoice" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Sales Report</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Queries" asp-controller="Print" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Queries Report </p>
                                    </a>
                                </li>
                            </ul>
                           
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    User Manager
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>

                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="CustomerDetails" asp-controller="User" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Customer</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="User" asp-area="Main" class="nav-link">
                                        <i class="far fa-circle nav-icon" style="font-size: small;"></i>
                                        <p>Manage Users</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @* <div class="container-fluid">
                    <div class="row mb-2">
                    <div class="col-sm-6">
                    <h1>Blank Page</h1>
                    </div>
                    <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                    </div>
                    </div>
                    </div><!-- /.container-fluid --> *@
            </section>

            <section class="content">
                @RenderBody()
            </section>

            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        @* <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.2.0-rc
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
            </footer> *@

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <script src="~/js/bundles/script.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

APP/Views/Shared/_Settings.cshtml
@using APP.Session
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContext
@{
    
}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="lnr lnr-user"></span>
     
    </a>
    <ul class="dropdown-menu ">
        <li class="single-cart-list">
            <a asp-area="Public" asp-controller="Home" asp-action="UserDetails"><span class="lnr lnr-cog"></span>.     User Infomation</a>
        </li>
        <li class="single-cart-list">
            <a asp-area="Public" asp-controller="Home" asp-action="ViewNonPaidOrder"><span class="lnr lnr-cart"></span>.     Outstanding Appoinment</a>
        </li>
        <li class="single-cart-list">
            <a asp-area="Public" asp-controller="Home" asp-action="ViewPaidOrder"><span class="lnr lnr-chart-bars"></span>.     My Appoinment</a>
        </li>
       
    </ul>
</li>
@*/.dropdown*@